### ISSUE TITLE
Different running modes result into different numbers of unit tests

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#146] opened 2016-03-04 02:33 UTC
When fixing #145 we noted the test number is different from system-wide and local installation of SOLVCON.

**Comment by yungyuc** [comment] 2017-12-02 12:18
@tai271828 See https://github.com/solvcon/solvcon/blob/c848cbbe8ec47b8a22190af55eb0c58595928c78/solvcon/__init__.py#L102 .  It's intentional to have `solvcon.test` to include only `solvcon.tests` and `solvcon.io.tests`.  The reason was so old that I forgot about it when making the [comment](https://github.com/solvcon/solvcon/issues/145#issuecomment-192033672) with issue #145 : `nosetests` doesn't work when I did it otherwise.

I close this issue for it is expected behavior.

**Closed as completed by yungyuc** 2017-12-02 12:18 UTC
Labels: bug, question, pastsolvcon
